apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderitem-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: OrderItem
  template:
    metadata:
      labels:
        app: OrderItem
    spec:
      containers:
      - name: orderitem
        image:  crfirstapi.azurecr.io/secondrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: orderitemsn

---
apiVersion: v1
kind: Service
metadata:
  name: orderitem
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: OrderItem
